import { useState, useEffect } from "react";
import { useSearchParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { Panel } from "../components/Panel";
import { KpiCard } from "../components/KpiCard";
import { DataTable, Column } from "../components/DataTable";
import { StatusBadge } from "../components/StatusBadge";
import {
  useDiagnostics,
  useProposals,
  useGenerateProposals,
  useApproveProposal,
  useRejectProposal,
  useApplyProposal,
  useApplyBatchProposals,
  useConfigChanges,
  useRevertChange,
  useScorecard,
  useLambdaScorecard,
} from "../api/hooks";

// ── Types ────────────────────────────────────────────────

interface ProposalRow extends Record<string, unknown> {
  proposal_id: string;
  strategy_id: string;
  proposal_type: string;
  target_component: string;
  confidence_score: number;
  expected_sharpe_improvement: number;
  expected_return_improvement: number;
  rationale: string;
  status: string;
  created_at: string;
}

interface ChangeRow extends Record<string, unknown> {
  change_id: string;
  proposal_id: string | null;
  strategy_id: string;
  change_type: string;
  target_component: string;
  sharpe_before: number | null;
  sharpe_after: number | null;
  sharpe_improvement: number | null;
  is_reverted: boolean;
  applied_at: string;
}

interface SectorBreakdown {
  sector: string;
  hit_rate: number;
  avg_error: number;
  count: number;
  avg_predicted: number;
  avg_realized: number;
}

interface ScorecardMiss extends Record<string, unknown> {
  decision_id: string;
  as_of_date: string;
  instrument_id: string;
  predicted_score: number;
  realized_return: number;
  hit: boolean;
  sector: string;
  error: number;
}

interface ScorecardData {
  horizon_days: number;
  total_predictions: number;
  hit_rate: number;
  spearman_rho: number;
  avg_predicted_score: number;
  avg_realized_return: number;
  sector_breakdown: SectorBreakdown[];
  top_misses: ScorecardMiss[];
  top_hits: ScorecardMiss[];
  date_range_start: string;
  date_range_end: string;
}

interface LambdaClusterAccuracy extends Record<string, unknown> {
  cluster_key: string;
  sector: string;
  soft_target_class: string;
  mae: number;
  rmse: number;
  direction_accuracy: number;
  count: number;
  avg_predicted: number;
  avg_actual: number;
}

interface LambdaScorecardData {
  market_id: string;
  total_predictions: number;
  mae: number;
  rmse: number;
  r_squared: number;
  direction_accuracy: number;
  avg_predicted: number;
  avg_actual: number;
  cluster_breakdown: LambdaClusterAccuracy[];
  date_range_start: string;
  date_range_end: string;
  data_source: string;
}

// ── Helpers ──────────────────────────────────────────────

function fmtPct(n: number): string {
  return `${(n * 100).toFixed(2)}%`;
}

function fmtFloat(n: number | null | undefined, decimals = 3): string {
  if (n == null) return "—";
  return Number(n).toFixed(decimals);
}

function timeSince(iso: string): string {
  const seconds = (Date.now() - new Date(iso).getTime()) / 1000;
  if (seconds < 60) return "just now";
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
  return `${Math.floor(seconds / 86400)}d ago`;
}

const STATUS_VARIANT: Record<string, "positive" | "negative" | "warning" | "info" | "neutral"> = {
  PENDING: "warning",
  APPROVED: "info",
  REJECTED: "negative",
  APPLIED: "positive",
  REVERTED: "neutral",
};

// ── Tooltip text ─────────────────────────────────────────

const TIP = {
  diagnostics: "Performance diagnostics from the Meta/Kronos intelligence layer. Analyzes backtest results to identify optimization opportunities.",
  proposals: "Configuration improvement proposals generated by analyzing backtest performance. Approve or reject each proposal, then apply approved changes.",
  changes: "Applied configuration changes and their performance outcomes. Revert changes that haven't improved Sharpe.",
};

// ── Component ────────────────────────────────────────────

type ScorecardTab = "assessment" | "lambda";

export default function Intelligence() {
  const [searchParams] = useSearchParams();
  const [strategyId, setStrategyId] = useState("MAIN");
  const [scorecardTab, setScorecardTab] = useState<ScorecardTab>("assessment");
  const briefId = searchParams.get("brief");

  // Scroll to proposals section when navigating from Dashboard brief link
  useEffect(() => {
    if (briefId) {
      // Brief ID from dashboard click — could be used for a detail modal in the future
      console.log("[Intelligence] brief param:", briefId);
    }
  }, [briefId]);

  const [horizonDays, setHorizonDays] = useState(21);

  const diagnostics = useDiagnostics(strategyId);
  const proposals = useProposals();
  const changes = useConfigChanges();
  const scorecard = useScorecard(horizonDays);
  const lambdaScorecard = useLambdaScorecard();
  const generateMutation = useGenerateProposals();
  const approveMutation = useApproveProposal();
  const rejectMutation = useRejectProposal();
  const applyMutation = useApplyProposal();
  const applyBatchMutation = useApplyBatchProposals();
  const revertMutation = useRevertChange();

  const diag = (diagnostics.data ?? {}) as Record<string, unknown>;
  const proposalList = (proposals.data ?? []) as ProposalRow[];
  const changeList = (changes.data ?? []) as ChangeRow[];
  const sc = scorecard.data as ScorecardData | undefined;
  const lsc = lambdaScorecard.data as LambdaScorecardData | undefined;

  const pendingCount = proposalList.filter((p) => p.status === "PENDING").length;
  const approvedCount = proposalList.filter((p) => p.status === "APPROVED").length;

  // ── Column definitions ─────────────────────────────────

  const proposalCols: Column<ProposalRow>[] = [
    {
      key: "status",
      label: "Status",
      width: "90px",
      render: (r) => <StatusBadge label={r.status} variant={STATUS_VARIANT[r.status] ?? "neutral"} />,
    },
    { key: "target_component", label: "Target" },
    { key: "proposal_type", label: "Type", width: "160px" },
    {
      key: "confidence_score",
      label: "Confidence",
      align: "right",
      width: "90px",
      render: (r) => fmtPct(r.confidence_score),
    },
    {
      key: "expected_sharpe_improvement",
      label: "Δ Sharpe",
      align: "right",
      width: "80px",
      render: (r) => {
        const v = r.expected_sharpe_improvement;
        const cls = v > 0 ? "text-positive" : v < 0 ? "text-negative" : "text-muted";
        return <span className={cls}>+{fmtFloat(v)}</span>;
      },
    },
    {
      key: "rationale",
      label: "Rationale",
      render: (r) => (
        <span className="truncate text-[11px] text-zinc-400" title={r.rationale}>
          {r.rationale}
        </span>
      ),
    },
    {
      key: "created_at",
      label: "Created",
      width: "80px",
      render: (r) => <span className="text-muted">{timeSince(r.created_at)}</span>,
    },
    {
      key: "proposal_id",
      label: "Actions",
      width: "180px",
      render: (r) => (
        <div className="flex gap-1">
          {r.status === "PENDING" && (
            <>
              <button
                className="rounded border border-positive/40 bg-positive/10 px-2 py-0.5 text-[10px] font-semibold text-positive hover:bg-positive/20 disabled:opacity-50"
                onClick={(e) => { e.stopPropagation(); approveMutation.mutate(r.proposal_id); }}
                disabled={approveMutation.isPending}
              >
                Approve
              </button>
              <button
                className="rounded border border-negative/40 bg-negative/10 px-2 py-0.5 text-[10px] font-semibold text-negative hover:bg-negative/20 disabled:opacity-50"
                onClick={(e) => { e.stopPropagation(); rejectMutation.mutate(r.proposal_id); }}
                disabled={rejectMutation.isPending}
              >
                Reject
              </button>
            </>
          )}
          {r.status === "APPROVED" && (
            <button
              className="rounded border border-accent/40 bg-accent/10 px-2 py-0.5 text-[10px] font-semibold text-accent hover:bg-accent/20 disabled:opacity-50"
              onClick={(e) => { e.stopPropagation(); applyMutation.mutate(r.proposal_id); }}
              disabled={applyMutation.isPending}
            >
              Apply
            </button>
          )}
        </div>
      ),
    },
  ];

  const changeCols: Column<ChangeRow>[] = [
    {
      key: "is_reverted",
      label: "Status",
      width: "80px",
      render: (r) => (
        <StatusBadge
          label={r.is_reverted ? "REVERTED" : "ACTIVE"}
          variant={r.is_reverted ? "neutral" : "positive"}
        />
      ),
    },
    { key: "target_component", label: "Target" },
    { key: "change_type", label: "Type", width: "160px" },
    {
      key: "sharpe_before",
      label: "Sharpe Before",
      align: "right",
      width: "100px",
      render: (r) => fmtFloat(r.sharpe_before),
    },
    {
      key: "sharpe_after",
      label: "Sharpe After",
      align: "right",
      width: "100px",
      render: (r) => fmtFloat(r.sharpe_after),
    },
    {
      key: "sharpe_improvement",
      label: "Δ Sharpe",
      align: "right",
      width: "80px",
      render: (r) => {
        if (r.sharpe_improvement == null) return <span className="text-muted">—</span>;
        const v = r.sharpe_improvement;
        const cls = v > 0 ? "text-positive" : v < 0 ? "text-negative" : "text-muted";
        return <span className={cls}>{v > 0 ? "+" : ""}{fmtFloat(v)}</span>;
      },
    },
    {
      key: "applied_at",
      label: "Applied",
      width: "80px",
      render: (r) => <span className="text-muted">{timeSince(r.applied_at)}</span>,
    },
    {
      key: "change_id",
      label: "Actions",
      width: "80px",
      render: (r) =>
        !r.is_reverted ? (
          <button
            className="rounded border border-warning/40 bg-warning/10 px-2 py-0.5 text-[10px] font-semibold text-warning hover:bg-warning/20 disabled:opacity-50"
            onClick={(e) => {
              e.stopPropagation();
              revertMutation.mutate({ id: r.change_id, reason: "Reverted via Intelligence UI" });
            }}
            disabled={revertMutation.isPending}
          >
            Revert
          </button>
        ) : null,
    },
  ];

  return (
    <div className="space-y-4">
      <PageHeader
        title="Kronos Intelligence"
        subtitle="Meta-orchestrator diagnostics, proposals & change tracking"
        onRefresh={() => {
          diagnostics.refetch();
          proposals.refetch();
          changes.refetch();
          scorecard.refetch();
          lambdaScorecard.refetch();
        }}
      />

      {/* Strategy Selector + Diagnostics KPIs */}
      <div className="flex items-end gap-3">
        <label className="block">
          <span className="text-[10px] uppercase text-muted">Strategy</span>
          <input
            className="mt-1 block w-48 rounded border border-border-dim bg-surface-overlay px-2 py-1.5 text-xs text-zinc-100"
            value={strategyId}
            onChange={(e) => setStrategyId(e.target.value)}
            placeholder="e.g. US_CORE_LONG_EQ"
          />
        </label>
        <button
          className="rounded border border-accent bg-accent/10 px-3 py-1.5 text-xs font-semibold text-accent hover:bg-accent/20 disabled:opacity-50"
          onClick={() => generateMutation.mutate(strategyId)}
          disabled={generateMutation.isPending || !strategyId}
        >
          {generateMutation.isPending ? "Generating..." : "Generate Proposals"}
        </button>
        {approvedCount > 0 && (
          <button
            className="rounded border border-positive bg-positive/10 px-3 py-1.5 text-xs font-semibold text-positive hover:bg-positive/20 disabled:opacity-50"
            onClick={() => applyBatchMutation.mutate(strategyId)}
            disabled={applyBatchMutation.isPending}
          >
            {applyBatchMutation.isPending ? "Applying..." : `Apply ${approvedCount} Approved`}
          </button>
        )}
      </div>

      {/* Diagnostics KPIs */}
      {!!diag.strategy_id && (
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">
          <KpiCard
            label="Overall Sharpe"
            value={fmtFloat(diag.overall_sharpe as number)}
            sentiment={(diag.overall_sharpe as number) > 1 ? "positive" : "neutral"}
          />
          <KpiCard
            label="Return"
            value={fmtPct(diag.overall_return as number)}
            sentiment={(diag.overall_return as number) > 0 ? "positive" : "negative"}
          />
          <KpiCard
            label="Volatility"
            value={fmtPct(diag.overall_volatility as number)}
            sentiment={(diag.overall_volatility as number) > 0.3 ? "warning" : "neutral"}
          />
          <KpiCard
            label="Max Drawdown"
            value={fmtPct(diag.max_drawdown as number)}
            sentiment={(diag.max_drawdown as number) < -0.2 ? "warning" : "neutral"}
          />
          <KpiCard label="Underperforming" value={String(diag.underperforming_count ?? 0)} />
          <KpiCard label="High Risk" value={String(diag.high_risk_count ?? 0)} sentiment={(diag.high_risk_count as number) > 0 ? "warning" : "neutral"} />
        </div>
      )}
      {diagnostics.isError && (
        <div className="rounded border border-warning/30 bg-warning/5 px-4 py-2 text-xs text-warning">
          Diagnostics unavailable: {String(diagnostics.error)}
        </div>
      )}

      {/* Proposals */}
      <Panel
        title={`Proposals (${pendingCount} pending · ${proposalList.length} total)`}
        tooltip={TIP.proposals}
      >
        <DataTable
          columns={proposalCols}
          data={proposalList}
          compact
          pageSize={15}
          emptyMessage="No proposals — generate proposals for a strategy to get started"
        />
      </Panel>

      {/* Prediction Scorecard */}
      <Panel
        title="Prediction Scorecard"
        tooltip="Prediction accuracy scorecards for assessment instrument scores and lambda opportunity density."
      >
        {/* Tab switcher */}
        <div className="mb-3 flex items-center gap-1">
          {(["assessment", "lambda"] as const).map((tab) => (
            <button
              key={tab}
              className={`rounded px-3 py-1 text-[11px] font-semibold ${
                scorecardTab === tab
                  ? "bg-accent/20 text-accent border border-accent/40"
                  : "bg-surface-overlay text-zinc-400 border border-border-dim hover:text-zinc-200"
              }`}
              onClick={() => setScorecardTab(tab)}
            >
              {tab === "assessment" ? "Assessment" : "Lambda"}
            </button>
          ))}
        </div>

        {/* ── Assessment Scorecard Tab ── */}
        {scorecardTab === "assessment" && (
          <>
            {/* Horizon selector */}
            <div className="mb-3 flex items-center gap-2">
              <span className="text-[10px] uppercase text-muted">Horizon</span>
              {[5, 21, 63].map((d) => (
                <button
                  key={d}
                  className={`rounded px-2 py-0.5 text-[10px] font-semibold ${
                    horizonDays === d
                      ? "bg-accent/20 text-accent border border-accent/40"
                      : "bg-surface-overlay text-zinc-400 border border-border-dim hover:text-zinc-200"
                  }`}
                  onClick={() => setHorizonDays(d)}
                >
                  {d}d
                </button>
              ))}
            </div>

            {scorecard.isLoading && <div className="py-6 text-center text-xs text-muted">Loading scorecard...</div>}
            {scorecard.isError && (
              <div className="rounded border border-warning/30 bg-warning/5 px-4 py-2 text-xs text-warning">
                Scorecard unavailable: {String(scorecard.error)}
              </div>
            )}

            {sc && sc.total_predictions > 0 && (
              <>
                {/* KPI row */}
                <div className="mb-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
                  <KpiCard
                    label="Hit Rate"
                    value={fmtPct(sc.hit_rate)}
                    sentiment={sc.hit_rate > 0.55 ? "positive" : sc.hit_rate < 0.45 ? "negative" : "neutral"}
                  />
                  <KpiCard
                    label="Spearman ρ"
                    value={fmtFloat(sc.spearman_rho)}
                    sentiment={sc.spearman_rho > 0.1 ? "positive" : sc.spearman_rho < -0.05 ? "negative" : "neutral"}
                  />
                  <KpiCard label="Predictions" value={String(sc.total_predictions)} />
                  <KpiCard label="Avg Predicted" value={fmtFloat(sc.avg_predicted_score, 4)} />
                  <KpiCard label="Avg Realized" value={fmtPct(sc.avg_realized_return)} />
                </div>

                {/* Sector breakdown */}
                {sc.sector_breakdown.length > 0 && (
                  <div className="mb-3">
                    <h4 className="mb-1 text-[10px] font-semibold uppercase text-muted">Sector Breakdown</h4>
                    <div className="grid gap-1">
                      {sc.sector_breakdown.map((s) => (
                        <div key={s.sector} className="flex items-center gap-2 rounded bg-surface-overlay px-2 py-1 text-xs">
                          <span className="w-32 truncate font-medium text-zinc-200">{s.sector}</span>
                          <span className={`w-16 text-right ${s.hit_rate > 0.55 ? "text-positive" : s.hit_rate < 0.45 ? "text-negative" : "text-zinc-400"}`}>
                            {fmtPct(s.hit_rate)}
                          </span>
                          <span className="w-12 text-right text-muted">{s.count}</span>
                          <div className="flex-1">
                            <div className="h-1.5 rounded-full bg-zinc-800">
                              <div
                                className={`h-1.5 rounded-full ${s.hit_rate > 0.55 ? "bg-positive" : s.hit_rate < 0.45 ? "bg-negative" : "bg-zinc-600"}`}
                                style={{ width: `${Math.min(s.hit_rate * 100, 100)}%` }}
                              />
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Top misses table */}
                {sc.top_misses.length > 0 && (
                  <div className="mb-3">
                    <h4 className="mb-1 text-[10px] font-semibold uppercase text-muted">Top Misses</h4>
                    <DataTable<ScorecardMiss>
                      columns={[
                        { key: "instrument_id", label: "Instrument", width: "140px" },
                        { key: "sector", label: "Sector", width: "120px" },
                        { key: "as_of_date", label: "Date", width: "90px" },
                        { key: "predicted_score", label: "Predicted", align: "right", width: "80px", render: (r) => fmtFloat(r.predicted_score, 4) },
                        { key: "realized_return", label: "Realized", align: "right", width: "80px", render: (r) => fmtPct(r.realized_return) },
                        { key: "error", label: "Error", align: "right", width: "80px", render: (r) => <span className="text-negative">{fmtFloat(r.error, 4)}</span> },
                      ]}
                      data={sc.top_misses.slice(0, 10)}
                      compact
                      emptyMessage="No misses"
                    />
                  </div>
                )}

                {/* Top hits table */}
                {sc.top_hits.length > 0 && (
                  <div>
                    <h4 className="mb-1 text-[10px] font-semibold uppercase text-muted">Top Hits</h4>
                    <DataTable<ScorecardMiss>
                      columns={[
                        { key: "instrument_id", label: "Instrument", width: "140px" },
                        { key: "sector", label: "Sector", width: "120px" },
                        { key: "as_of_date", label: "Date", width: "90px" },
                        { key: "predicted_score", label: "Predicted", align: "right", width: "80px", render: (r) => fmtFloat(r.predicted_score, 4) },
                        { key: "realized_return", label: "Realized", align: "right", width: "80px", render: (r) => fmtPct(r.realized_return) },
                      ]}
                      data={sc.top_hits.slice(0, 10)}
                      compact
                      emptyMessage="No hits"
                    />
                  </div>
                )}

                <div className="mt-2 text-[10px] text-muted">
                  Date range: {sc.date_range_start} → {sc.date_range_end}
                </div>
              </>
            )}

            {sc && sc.total_predictions === 0 && (
              <div className="py-6 text-center text-xs text-muted">No scored predictions found — run the outcome backfill first</div>
            )}
          </>
        )}

        {/* ── Lambda Scorecard Tab ── */}
        {scorecardTab === "lambda" && (
          <>
            {lambdaScorecard.isLoading && <div className="py-6 text-center text-xs text-muted">Loading lambda scorecard...</div>}
            {lambdaScorecard.isError && (
              <div className="rounded border border-warning/30 bg-warning/5 px-4 py-2 text-xs text-warning">
                Lambda scorecard unavailable: {String(lambdaScorecard.error)}
              </div>
            )}

            {lsc && lsc.total_predictions > 0 && (
              <>
                {/* KPI row */}
                <div className="mb-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">
                  <KpiCard
                    label="Direction Acc."
                    value={fmtPct(lsc.direction_accuracy)}
                    sentiment={lsc.direction_accuracy > 0.55 ? "positive" : lsc.direction_accuracy < 0.45 ? "negative" : "neutral"}
                  />
                  <KpiCard label="MAE" value={fmtFloat(lsc.mae, 4)} />
                  <KpiCard label="RMSE" value={fmtFloat(lsc.rmse, 4)} />
                  <KpiCard
                    label="R²"
                    value={fmtFloat(lsc.r_squared, 4)}
                    sentiment={lsc.r_squared > 0.1 ? "positive" : lsc.r_squared < 0 ? "negative" : "neutral"}
                  />
                  <KpiCard label="Predictions" value={String(lsc.total_predictions)} />
                  <KpiCard label="Source" value={lsc.data_source} />
                </div>

                {/* Cluster breakdown */}
                {lsc.cluster_breakdown.length > 0 && (
                  <div className="mb-3">
                    <h4 className="mb-1 text-[10px] font-semibold uppercase text-muted">Cluster Breakdown</h4>
                    <DataTable<LambdaClusterAccuracy>
                      columns={[
                        { key: "sector", label: "Sector", width: "140px" },
                        { key: "soft_target_class", label: "STAB Class", width: "100px" },
                        {
                          key: "direction_accuracy",
                          label: "Dir. Acc.",
                          align: "right",
                          width: "80px",
                          render: (r) => (
                            <span className={r.direction_accuracy > 0.55 ? "text-positive" : r.direction_accuracy < 0.45 ? "text-negative" : "text-zinc-400"}>
                              {fmtPct(r.direction_accuracy)}
                            </span>
                          ),
                        },
                        { key: "mae", label: "MAE", align: "right", width: "80px", render: (r) => fmtFloat(r.mae, 4) },
                        { key: "rmse", label: "RMSE", align: "right", width: "80px", render: (r) => fmtFloat(r.rmse, 4) },
                        { key: "count", label: "Count", align: "right", width: "60px" },
                        { key: "avg_predicted", label: "Avg Pred.", align: "right", width: "80px", render: (r) => fmtFloat(r.avg_predicted, 4) },
                        { key: "avg_actual", label: "Avg Actual", align: "right", width: "80px", render: (r) => fmtFloat(r.avg_actual, 4) },
                      ]}
                      data={lsc.cluster_breakdown}
                      compact
                      pageSize={20}
                      emptyMessage="No clusters"
                    />
                  </div>
                )}

                <div className="mt-2 text-[10px] text-muted">
                  Date range: {lsc.date_range_start} → {lsc.date_range_end} · Market: {lsc.market_id}
                </div>
              </>
            )}

            {lsc && lsc.total_predictions === 0 && (
              <div className="py-6 text-center text-xs text-muted">No lambda predictions found — ensure universe_members have lambda_score in reasons JSON</div>
            )}
          </>
        )}
      </Panel>

      {/* Config Changes */}
      <Panel
        title={`Config Changes (${changeList.length})`}
        tooltip={TIP.changes}
      >
        <DataTable
          columns={changeCols}
          data={changeList}
          compact
          pageSize={15}
          emptyMessage="No configuration changes applied yet"
        />
      </Panel>
    </div>
  );
}
