"""Static economic-event calendar.

The data here covers the highest-impact IV events on the underlyings
Prometheus actually trades. Two strategies:

1. **Deterministic by rule** — NFP (first Friday), EIA petroleum
   (Wednesday), EIA natural gas (Thursday), USDA WASDE (~12th),
   CPI (~13th). Generated by ``rule_dates_for_year``.
2. **Hardcoded from public schedule** — FOMC, OPEC+. Fed publishes
   FOMC dates a year ahead; OPEC schedules its own meetings. See
   ``_FOMC_DATES`` and ``_OPEC_DATES`` for the live tables — update
   them annually until ``Phase 5.3`` replaces this with a dynamic
   API pull.

Per-symbol sensitivity ``_SYMBOL_EVENT_MAP`` is the second source of
truth: which event categories matter for which underlying. SPY/VIX
care about all macro events; GC cares about Fed + CPI; CL/BZ care
about EIA petroleum + OPEC; etc.

Vintage notes:
* FOMC 2026 — per Fed published 2026 schedule
* OPEC+ — known meetings as of 2026-06; refresh as new dates
  are announced
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta
from enum import Enum
from typing import Iterable

# ── Event categories ────────────────────────────────────────────────


class EventKind(str, Enum):
    FOMC = "FOMC"
    CPI = "CPI"
    NFP = "NFP"
    EIA_PETROLEUM = "EIA_PETROLEUM"
    EIA_NATGAS = "EIA_NATGAS"
    USDA_WASDE = "USDA_WASDE"
    OPEC = "OPEC"


@dataclass(frozen=True)
class EconomicEvent:
    """One scheduled IV-relevant event."""
    kind: EventKind
    event_date: date
    note: str = ""


# ── Hardcoded irregular schedules ──────────────────────────────────


# Federal Reserve 2026 FOMC meeting dates (final day of each two-day
# meeting — the date markets price the policy statement on).
# Source: federalreserve.gov FOMC calendar, retrieved 2026-06.
_FOMC_DATES: tuple[date, ...] = (
    date(2026, 1, 28),
    date(2026, 3, 18),
    date(2026, 4, 29),
    date(2026, 6, 17),
    date(2026, 7, 29),
    date(2026, 9, 16),
    date(2026, 10, 28),
    date(2026, 12, 9),
    # Forward placeholders for 2027 — update from Fed publication when out
    date(2027, 1, 27),
    date(2027, 3, 17),
    date(2027, 4, 28),
)


# OPEC+ JMMC + Ministerial Meeting dates known as of 2026-06.
# Includes announced meetings; ad-hoc meetings may be added.
_OPEC_DATES: tuple[date, ...] = (
    date(2026, 6, 1),
    date(2026, 8, 3),
    date(2026, 10, 5),
    date(2026, 12, 1),
    date(2027, 2, 1),
)


# ── Rule-based event date generators ───────────────────────────────


def _first_friday(year: int, month: int) -> date:
    d = date(year, month, 1)
    while d.weekday() != 4:   # Friday = 4
        d += timedelta(days=1)
    return d


def _every_weekday_for_year(year: int, weekday: int) -> list[date]:
    """All dates in `year` falling on `weekday` (Mon=0 … Sun=6)."""
    out: list[date] = []
    d = date(year, 1, 1)
    while d.weekday() != weekday:
        d += timedelta(days=1)
    while d.year == year:
        out.append(d)
        d += timedelta(days=7)
    return out


def nfp_dates_for_year(year: int) -> list[date]:
    """BLS NFP release: first Friday of each month, 8:30 ET."""
    return [_first_friday(year, m) for m in range(1, 13)]


def cpi_dates_for_year(year: int) -> list[date]:
    """BLS CPI release: typically the 10th-15th; ~13th as a proxy.

    Real release day varies year-to-year by ±2 days. Phase 5.3 pulls
    the exact BLS schedule via API. For trigger gates within a few
    days of an event, the proxy is sufficient.
    """
    return [date(year, m, 13) for m in range(1, 13)]


def eia_petroleum_dates_for_year(year: int) -> list[date]:
    """EIA Weekly Petroleum Status Report: every Wednesday 10:30 ET."""
    return _every_weekday_for_year(year, weekday=2)  # Wednesday


def eia_natgas_dates_for_year(year: int) -> list[date]:
    """EIA Weekly Natural Gas Storage Report: every Thursday 10:30 ET."""
    return _every_weekday_for_year(year, weekday=3)  # Thursday


def wasde_dates_for_year(year: int) -> list[date]:
    """USDA WASDE: ~10th-12th of each month; use 12th as proxy."""
    return [date(year, m, 12) for m in range(1, 13)]


def fomc_dates() -> tuple[date, ...]:
    return _FOMC_DATES


def opec_dates() -> tuple[date, ...]:
    return _OPEC_DATES


# ── Symbol → event-kind sensitivity ────────────────────────────────


# Which events meaningfully move IV on each underlying. Anything not
# listed is treated as "no calendar awareness for this symbol".
_SYMBOL_EVENT_MAP: dict[str, frozenset[EventKind]] = {
    # Index options
    "SPY": frozenset({EventKind.FOMC, EventKind.CPI, EventKind.NFP}),
    "VIX": frozenset({EventKind.FOMC, EventKind.CPI, EventKind.NFP}),
    # Sector ETFs we trade via CONVEX templates
    "XLE": frozenset({EventKind.EIA_PETROLEUM, EventKind.OPEC, EventKind.FOMC}),
    "XLK": frozenset({EventKind.FOMC, EventKind.CPI}),
    "XLF": frozenset({EventKind.FOMC, EventKind.CPI}),
    # Commodity futures-options (the new COMMODITY sleeve)
    "CL": frozenset({EventKind.EIA_PETROLEUM, EventKind.OPEC}),
    "BZ": frozenset({EventKind.EIA_PETROLEUM, EventKind.OPEC}),
    "NG": frozenset({EventKind.EIA_NATGAS}),
    "ZW": frozenset({EventKind.USDA_WASDE}),
    "GC": frozenset({EventKind.FOMC, EventKind.CPI}),
    "HG": frozenset(),   # no clean IV-event mapping in v1; Phase 5.3 may add China PMI
}


def event_kinds_for_symbol(symbol: str) -> frozenset[EventKind]:
    """Return the set of EventKinds that move IV on this symbol."""
    return _SYMBOL_EVENT_MAP.get(symbol.upper(), frozenset())


# ── Event lookup helpers ───────────────────────────────────────────


def _db_events(
    today: date,
    end: date,
    wanted: set[EventKind],
) -> list[EconomicEvent]:
    """Pull events from the shared ``economic_events`` table (populated
    by ``apatheon.data_ingestion.te_calendar``).

    Returns [] silently on any DB error so callers can fall back to the
    hardcoded calendar — never breaks trigger evaluation.
    """
    try:
        from apatheon.core.database import get_db_manager
        db = get_db_manager()
        wanted_str = [k.value for k in wanted]
        with db.get_runtime_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT event_date, kind, event_name
                      FROM economic_events
                     WHERE event_date > %s AND event_date <= %s
                       AND kind = ANY(%s)
                  ORDER BY event_date
                    """,
                    (today, end, wanted_str),
                )
                rows = cur.fetchall()
    except Exception:
        return []
    out: list[EconomicEvent] = []
    for ev_date, kind_str, name in rows:
        try:
            kind = EventKind(kind_str)
        except ValueError:
            continue
        out.append(EconomicEvent(kind, ev_date, name or ""))
    return out


def upcoming_events(
    today: date,
    *,
    horizon_days: int = 30,
    kinds: Iterable[EventKind] | None = None,
    use_db: bool = True,
) -> list[EconomicEvent]:
    """All scheduled events on (today, today + horizon_days].

    Filtered by ``kinds`` if provided. When ``use_db`` is True (default)
    and the shared ``economic_events`` table has rows, those win;
    otherwise the function falls back to the hardcoded rule-based +
    static dates below.
    """
    wanted = set(kinds) if kinds is not None else set(EventKind)
    end = today + timedelta(days=horizon_days)

    if use_db:
        db_out = _db_events(today, end, wanted)
        if db_out:
            return db_out

    out: list[EconomicEvent] = []

    if EventKind.FOMC in wanted:
        for d in fomc_dates():
            if today < d <= end:
                out.append(EconomicEvent(EventKind.FOMC, d, "Fed policy statement"))
    if EventKind.OPEC in wanted:
        for d in opec_dates():
            if today < d <= end:
                out.append(EconomicEvent(EventKind.OPEC, d, "OPEC+ meeting"))
    if EventKind.CPI in wanted:
        for d in cpi_dates_for_year(today.year) + cpi_dates_for_year(today.year + 1):
            if today < d <= end:
                out.append(EconomicEvent(EventKind.CPI, d, "BLS CPI release"))
    if EventKind.NFP in wanted:
        for d in nfp_dates_for_year(today.year) + nfp_dates_for_year(today.year + 1):
            if today < d <= end:
                out.append(EconomicEvent(EventKind.NFP, d, "BLS NFP release"))
    if EventKind.EIA_PETROLEUM in wanted:
        for d in eia_petroleum_dates_for_year(today.year) + eia_petroleum_dates_for_year(today.year + 1):
            if today < d <= end:
                out.append(EconomicEvent(EventKind.EIA_PETROLEUM, d, "EIA Weekly Petroleum Status"))
    if EventKind.EIA_NATGAS in wanted:
        for d in eia_natgas_dates_for_year(today.year) + eia_natgas_dates_for_year(today.year + 1):
            if today < d <= end:
                out.append(EconomicEvent(EventKind.EIA_NATGAS, d, "EIA Weekly Natural Gas Storage"))
    if EventKind.USDA_WASDE in wanted:
        for d in wasde_dates_for_year(today.year) + wasde_dates_for_year(today.year + 1):
            if today < d <= end:
                out.append(EconomicEvent(EventKind.USDA_WASDE, d, "USDA WASDE"))

    out.sort(key=lambda e: e.event_date)
    return out


def next_iv_events(
    symbol: str,
    today: date,
    *,
    horizon_days: int = 30,
) -> list[EconomicEvent]:
    """Next events on ``today + horizon_days`` that move IV for ``symbol``."""
    kinds = event_kinds_for_symbol(symbol)
    if not kinds:
        return []
    return upcoming_events(today, horizon_days=horizon_days, kinds=kinds)


def days_to_iv_event(symbol: str, today: date, *, horizon_days: int = 30) -> int | None:
    """Days until the next IV-relevant event for ``symbol``, or None."""
    events = next_iv_events(symbol, today, horizon_days=horizon_days)
    if not events:
        return None
    return (events[0].event_date - today).days


def near_iv_event(
    symbol: str,
    today: date,
    *,
    window_days: int = 2,
) -> EconomicEvent | None:
    """Return the next IV-relevant event if it falls inside the window.

    ``window_days`` is the number of calendar days to scan ahead, INCLUSIVE
    of today. So ``window_days=2`` means "today + tomorrow + day after."
    """
    events = next_iv_events(symbol, today, horizon_days=window_days)
    return events[0] if events else None
